### ISSUE TITLE
default user does not have sufficient permissions, which results in failing to use installed packages

### ISSUE THREAD

**Issue by marvingfx** [qdm12/latexdevcontainer#10]
Initially, when running `texhash`, something like the following shows up:
```
texhash: /usr/local/texlive/2020/texmf-config/ls-R: no write permission, skipping...
texhash: /usr/local/texlive/2020/texmf-dist/ls-R: no write permission, skipping...
texhash: /usr/local/texlive/2020/texmf-var/ls-R: no write permission, skipping...
texhash: /usr/local/texlive/texmf-local/ls-R: no write permission, skipping...
texhash: Done.
```

This means that packages installed via `tlmgr` are not picked up.

This can be fixed by running the following command fixes this `sudo chown -R 1000:1000 /usr/local/texlive`. After this command you are able to run texhash successfully. I could create a pull request, but I'm sure a more elegant solution can be found.

**Comment by qdm12** [comment]
Thanks for pointing this out! It should be fixed now.
