### ISSUE TITLE
How to install package `ngerman`?

### ISSUE THREAD

**Issue by hediet** [qdm12/latexdevcontainer#11]
First: Nice work 😉 If I get this devcontainer to work, this will be awesome!
I didn't yet have the flawless LaTex-experience I hoped I would get with this, but I can imagine that this is the way to get it.

Basically, I have [this problem](https://tex.stackexchange.com/questions/167077/package-babel-error-unknown-option-ngerman?noredirect=1&lq=1):
```
/usr/local/texlive/2020/texmf-dist/tex/generic/babel/babel.sty:1119: Package babel Error: Unknown option `ngerman'. Either you misspelled it
(babel)                or the language definition file ngerman.ldf was not found.
```

Caused by this I guess:
```
\usepackage[ngerman,english]{babel}
```

Sadly, `sudo apt-get install texlive-lang-german` in the dev-container didn't fix it for me. I guess this might be due to how latex is installed in the dev container.

I'm sorry to say that I'm a total linux/latex noob (but I guess noobs are the target for this devcontainer anyways).

How can I make `ngerman` work?

**Comment by qdm12** [comment]
From the top of my head, try `tlmgr install ngermax` maybe followed by `texhash`.

The OS is Alpine (again from the top my just woke up brain 😄) so the package manager is `apk` for example `apk add curl`.

I'll get back to you in a few hours after my day job to debug it myself.

Thanks a lot for the sponsorship, I'll do my best to make it worth it!

**Comment by hediet** [comment]
Hey, thank you for your quick reply and no worries 😉
My sponsorship is nothing, please don't stress yourself!

> tlmgr install german

I already tried that.
I just ran `texhash`, but I have the same problem.

**Comment by qdm12** [comment]
Ok that was a bit of archeology work haha but this seems to make it compile fine for me:

```sh
tlmgr install babel-german
```

You could use `sudo apt-get install` as well but that installs another version of texlive which opens a whole new can of worms... Try to keep it to `tlmgr` if you can. Also I found the `babel-german` by searching the content of the debian package https://packages.debian.org/sid/texlive-lang-german 😉 

Let me know if it doesn't work.

**Comment by hediet** [comment]
Thank you! I think it worked.

However, I'm back to Overleaf again...
Their PDF compiletimes are significantly lower (like 10s vs 30s) and I have way fewer problems with missing packages/minted/svg.
Overleafs editor is not that great though.
It would be so awesome to have the Overleaf experience in VS Code!

**Comment by qdm12** [comment]
> Thank you! I think it worked.

👍 

> However, I'm back to Overleaf again...

I can't argue, overleaf is great.

I did this container because I was working on Latex documents I didn't want online and shared with Overleaf.

> Their PDF compiletimes are significantly lower (like 10s vs 30s)

Hmm that's strange, mine compile under 5 seconds for a ~10 pages document on an 8 cores desktop running Windows 10 with Docker Desktop in its VM (not WSL). But maybe that doesn't scale for more pages/more complex graphs etc., I haven't tried yet.

> have way fewer problems with missing packages/minted/svg

So you could install the entire texlive with all the packages, that's what most people do when installing it locally, because its package manager is not so great.
But I'm a 'small docker image maniac' so I installed the bare minimum texlive with `tlmgr` so that you can install packages you need only. Maybe I'll do another fat Docker image with another tag to ease the package installation.

**Comment by hediet** [comment]
> Maybe I'll do another fat Docker image with another tag to ease the package installation.

I think that might be useful! I figured out how to create my own dev container with a full texlive installation (it was not that hard), but all the nice tooling (like formatting etc.) is not configured.

**Comment by qdm12** [comment]
I made the image `qmcgaw/latexdevcontainer:latest-full`,  you just have to substitute it in the .devcontainer/Dockerfile.

But it's a fat 4.2GB image lol, and takes 25 minutes to build 😄 Not ideal, but it should have everything you need.
