### ISSUE TITLE
Autobuild Does Not Work

### ISSUE THREAD

**Issue by hediet** [qdm12/latexdevcontainer#12]
Steps to reproduce:

About:
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

1. Run this in wsl:
```sh
mkdir .devcontainer
cd .devcontainer
wget -q https://raw.githubusercontent.com/qdm12/latexdevcontainer/master/.devcontainer/devcontainer.json
wget -q https://raw.githubusercontent.com/qdm12/latexdevcontainer/master/.devcontainer/docker-compose.yml
```

2. Create `foo.tex` with this content:
```latex
\documentclass{article}

\begin{document}
hello world 123
\end{document}
```

3. Click on "Build LaTeX" project in LaTeX Workshop. It builds the pdf.
4. Change `foo.tex` and save the file. Nothing happens.

Probably something needs to be configured.

This setting does not help though:

```
"latex-workshop.latex.autoBuild.run": "onSave"
```

**Comment by qdm12** [comment]
> Probably something needs to be configured.

I just tried, running on a Windows host with VSCode 1.52.1 and it works. The big difference here is I still run Docker with Docker Desktop in its (hidden/behind the scene) VM and don't use WSL. I believe I had the problem where file changes notifications are not propagated correctly with WSL and Docker containers. I don't think there is really a solution except dropping WSL unfortunately. You could do some more testing with containers and bind mounts.

> Run this in wsl:

Tiny FYI you can now use [devtainr](https://github.com/qdm12/devtainr#usage) with

```sh
devtainr -dev latex -name projectname
```

😉

**Comment by hediet** [comment]
> The big difference here is I still run Docker with Docker Desktop in its (hidden/behind the scene) VM and don't use WSL.

Sorry, I was not very precise. I only used WSL to download the devcontainer config files.
I opened the folder in a VS Code Dev Container (using Docker).

Surprisingly, it works now. I guess something restarted in between, I don't remember what I did differently.

> Tiny FYI you can now use devtainr with

That is a really good idea!
I hope eventually VS Code will offer an easier way to setup dev containers.

**Comment by qdm12** [comment]
> using Docker

But are you using Docker with the hyperv VM or WSL? 🧐

> Surprisingly, it works now

yes sometimes just rebuilding the container from the VS Code command palette unclogs things 😉 

> I hope eventually VS Code will offer an easier way to setup dev containers.

Yeah, although it's quite awesome what they've done with dev containers already. Plus there is a lot of different ways to structure your files in that directory. I picked one that I share across my repositories so my tool works great with them, but that's not the case for everyone

**Comment by hediet** [comment]
I understand now. Yeah, I guess I upgraded to WSL 2 some time ago, so I think my docker installation uses wsl and not hyper-v. I find all this virtualization stuff crazy :D

> Yeah, although it's quite awesome what they've done with dev containers already.

Yes! I see a bright future for dev containers!

> Plus there is a lot of different ways to structure your files in that directory

You mean how the latex sources are structured? Or how the dev container is structured?

**Comment by qdm12** [comment]
> I upgraded to WSL 2 some time ago, so I think my docker installation uses wsl and not hyper-v. I find all this virtualization stuff crazy

I was a bit disappointed with Docker and WSL 2. It first tried WSL 1 which didn't support Docker so that a big no-no for me. And then WSL 2 has bind mount issues and memory leaks issue too (because of it caching files). So I'm still stuck on the pre-WSL days of running a full hyperv machine (but no setup required though, Docker Desktop handles that for you). And there again, it's not perfect either, I have file permission with bind mounts not working correctly A LOT 😄 

I also have a Linux machine which works beautifully with development containers though.

> Yes! I see a bright future for dev containers!

Yeah plus there is that Github codespaces I haven't tried yet which is another aspect of it. Having your dev environment in your browser and benefiting from fast cloud hardware is definitely a great thing too.

> Plus there is a lot of different ways to structure your files in that directory

No 😄 How to files are structured in the `.devcontainer` directory.
