### ISSUE TITLE
Docker socket broken after closing remote connection

### ISSUE THREAD

**Issue by frutti93** [qdm12/latexdevcontainer#13]
Hi there,

thanks for creating this! However I am having an issue. Setting up everything works really smooth, working within the container as well. But after I am finished working and close the remote connection, my docker socket seems to be broken somehow. Sudo access works, but VSCode tells me I have no permission to start anything and the Docker extension itself also cannot access the socket anymore. My regular user, who is in the docker group has no permissions to do anything after this as well.

Restarting the socket solves the problem, but this is just a workaround. Unfortunately logs do not show anything suspicious as well.

Did anyone encounter this as well?

```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.1-arch1-1
```

and my Docker version:
```
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.16
 Git commit:        48d30b5b32
 Built:             Sun Feb 21 15:36:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16
  Git commit:       46229ca1d8
  Built:            Sun Feb 21 15:35:53 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by frutti93** [comment]
It seems i posted this a little to early, while playing around I removed the line mounting the docker socket from the compose file and now everything seems to work.

**Comment by qdm12** [comment]
Ah ok no problem! Enjoy!
