### ISSUE TITLE
Allow older version of TexLive

### ISSUE THREAD

**Issue by Skrallexxx** [qdm12/latexdevcontainer#14]
I think it would be great if this could support older versions of TexLive using the image tags.

Specifically for me, I need 2017 as the tabu package since then has been broken in regards to supporting colours.

**Comment by qdm12** [comment]
Sorry I lost track of the issue.

You can build the image using the build argument `--build-arg TEXLIVE_VERSION=2017` and see #16 on how to allow tlmgr to use texlive 2017. Let me know if you need more help.

**Comment by Skrallexxx** [comment]
Perfect, thanks. I believe between #16 and #17, all the needed info should be there to change the version to an older or newer version.
