### ISSUE TITLE
tlmgr doesn't work anymore

### ISSUE THREAD

**Issue by thchriswiesmann** [qdm12/latexdevcontainer#15]
I'm having trouble running `tlmgr install` or `tlmgr update --self` in the container. Seems like there is a problem with the repository due to the release of TeX Live 2021.

I get the following output in the console:
```
tlmgr: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

**Comment by qdm12** [comment]
Noted, I'll look into it in the coming days. Thanks for creating an issue!

**Comment by qdm12** [comment]
Changed it to 2021, it seems to work now.

In the future, if I disappear for whatever reason, you can use

```sh
docker build -t qmcgaw/latexdevcontainer --build-arg TEXLIVE_VERSION=2022 https://github.com/qdm12/latexdevcontainer.git
```

And it *should* build and upgrade to the 2022 TexLive version for example.
