### ISSUE TITLE
Update to TexLive 2021

### ISSUE THREAD

**Issue by Skrallexxx** [qdm12/latexdevcontainer#16]
Texlive 2021 is now the latest release and 2020 is considered 'historic', and tlmgr will complain when trying to install new packages into Texlive 2020.

This can be (temporarily) resolved by adding the following line to the devcontainer Dockerfile:

`RUN tlmgr option repository ftp://tug.org/historic/systems/texlive/2020/tlnet-final/`

**Comment by qdm12** [comment]
Ah interesting. Although is there a point now that it's using texlive 2021?

**Comment by Skrallexxx** [comment]
I realise this has actually already happened in b69bd6295083fd8d67601d69e249d908d67ccac7, however the readme has not yet been updated to reflect that 2021 will be used.

Additionally, I think it may be useful to have the above information on how to change the repository for anyone who for some reason MUST stay on 2020 for the moment. This issue should be closed once the readme is updated.
