### ISSUE TITLE
How to add custom .cls/.sty?

### ISSUE THREAD

**Issue by fortierq** [qdm12/latexdevcontainer#18]
I would like to use a custom .cls file for my project. Since I want to version it, I would like to put this file in /workspace/. However even after modifying TEXHOME to /workspace/, latexmk can't find my .cls.
How can I do it properly?

**Comment by fortierq** [comment]
The following line in docker-compose.yml solved my problem:
```
    environment:
      - TEXMFHOME=/workspace/texmf

```

**Comment by qdm12** [comment]
Hi there! First of all thanks for #19 

Sorry I didn't answer in time, but I'm glad you figured it out!

To be completely honest, I'm not that 100% familiar with latex, I really just use it from time to time 😉  So I probably could not had helped much anyway!
