### ISSUE TITLE
Latexindent args error

### ISSUE THREAD

**Issue by fortierq** [qdm12/latexdevcontainer#20]
Hello,
What is the purpose of the custom latexindent arguments?
```
        "latex-workshop.latexindent.args": [
            "-c",
            "%DIR%/",
            "%TMPFILE%",
            "-y=\"defaultIndent: '%INDENT%',onlyOneBackUp: 1\"",
        ],
```

It gives me errors (Formatting failed) on save.
When I remove those args, it works.

**Comment by qdm12** [comment]
It's arguments that worked with latexindent last time I used it (probably at least 6 months ago). Does it format your Latex code on save automatically without these arguments as well?

**Comment by qdm12** [comment]
Updated arguments are

```json
        "latex-workshop.latexindent.args": [
            "-c",
            "%DIR%/",
            "%TMPFILE%",
            "-y=defaultIndent: '%INDENT%'"
        ]
```

- `-c %DIR%/` means to save temporary file in the current workspace used by Latex workshop. The variable `%DIR%` is made available by the latex workshop extension.
- `%TMPFILE%` is to designate the file to format, which is a temporary file created by Latex workshop (you won't see it really). The variable `%TMPFILE%` is made available by the latex workshop extension.
- `-y=\"defaultIndent: '%INDENT%'\"` is the yml configuration to use for latexindent, and `%INDENT%` is the detected file indent made available by the latex workshop extension.
