### ISSUE TITLE
tlmgr broken

### ISSUE THREAD

**Issue by michidk** [qdm12/latexdevcontainer#26]
Today I rebuilt my devcontainer and now tlgmr seems to be broken.
When trying to install any package, I get the following error:
```
/workspace master !4 ?1 ❯ tlmgr install microtype                                                                                                                                                                                           root@65a11e754b12
(running on Debian, switching to user mode!)
(see /usr/share/doc/texlive-base/README.tlmgr-on-Debian.md)
TLPDB: not a directory, not loading: /root/texmf
tlmgr: user mode not initialized, please read the documentation!
```

According to [StackOverflow](https://tex.stackexchange.com/questions/137428/tlmgr-cannot-setup-tlpdb), `tlmgr init-usertree` should fix the issue. But then I get the following error:
```
/workspace master !4 ?1 ❯ tlmgr install microtype                                                                                                                                                                                           root@65a11e754b12
(running on Debian, switching to user mode!)
(see /usr/share/doc/texlive-base/README.tlmgr-on-Debian.md)

tlmgr: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

**Comment by michidk** [comment]
Actually, it seems like the issue was to run `apt-get install -y texlive-lang-german` before running tlmgr.
Is there another way to install the german language support package?

**Comment by michidk** [comment]
Okay, it seems like installing latex addons using the package manager is not supported with this approach. 
The packages have to be installed manually with tlmgr (e.g. `tlmgr install german babel-german`).

**Comment by qdm12** [comment]
Hey @michidk sorry I didn't get back to you earlier.

What's the problem with installing them with tlmgr though? Or do you need to apt-get install them beforehand? Thanks!

**Comment by michidk** [comment]
Hey @qdm12 thanks for getting back to me. It is just more convenient to install all those packages with one command without having to deal with the specifics. I also just wasn't aware that installing `texlive-lang-german` with apt-get really breaks tlmgr.

**Comment by qdm12** [comment]
That makes sense, sorry I have no idea why it breaks tlmgr...

TeX live is installed a bit manually in the docker image so that might cause `apt` to re-install it and break tlmgr. But that's just a wild guess.
