### ISSUE TITLE
Do we need somename.synctex.gz and how to use "latex-workshop.latex.outDir": "./out",

### ISSUE THREAD

**Issue by shinokada** [qdm12/latexdevcontainer#3]
Q1. After saving it creates synctex.gz, for example, percent.synctex.gz file. 
Do we need this?

Q2. I used to use "latex-workshop.latex.outDir": "./out", in VS Code setting. Where can I add this? Is it possible to output to the out directory? I tried to put it in the devcontainer.json settings field, but it didn't work.

**Comment by qdm12** [comment]
1. No you don't, it's just for some pdf viewer I think and is generated by default
2. When you modify devcontainer.json it will only take effect if you rebuild the container. You can however edit the vscode settings in the development container (press CTRL+`,` and change the tab to container settings) which changes settings although won't persist on a container image rebuild.
You can also add a file at /workspace/.vscode/settings.json which values you want to override and this will take precedence.

I usually modify the container settings and update devcontainer.json at the same time so it's persistent.

**Comment by qdm12** [comment]
As I recall, I tried to remove this generated synctex.gz auto-generation but I think it's the LateX workshop extension generating it every time. Feel free to comment if you have found a way to deactivate it.
