### ISSUE TITLE
Question: qmcgaw/devtainr vs qmcgaw/latexdevcontainer

### ISSUE THREAD

**Issue by turbotimon** [qdm12/latexdevcontainer#33]
First of all, this is great! Thanks a lot❤

I'm a little confused on how to use it, because the README and other files mention `qmcgaw/latexdevcontainer` as well as `qmcgaw/devtainr`. Are these different containers or synonyms? When should you use which one?

(Please forgive me if this is a stupid question as I'm pretty new to dev containers)

Referring to:

> - **Two Docker images**:
    - `qmcgaw/latexdevcontainer:latest` (default) which uses the TexLive basic scheme and has an uncompressed image size of 467MB
    - `qmcgaw/latexdevcontainer:latest-full` which uses the TexLive full scheme and has an uncompressed image size of 4.2GB - most packages you would need are already installed.

and

> 1. Setup your configuration files
    - With style 💯

        ```sh
        docker run -it --rm -v "/yourrepopath:/repository" qmcgaw/devtainr:v0.4.0 -dev latex -path /repository -name projectname
        ```

**Comment by qdm12** [comment]
Hello, no problem 😉 
`qmcgaw/devtainr` is just an image to setup your vscode files to run a certain dev environment (i.e. latex). See https://github.com/qdm12/devtainr

You can also just use the binary directly without the docker image from https://github.com/qdm12/devtainr/releases/tag/v0.6.0 or just copy paste each file from the .devcontainer directory in this repository.
