### ISSUE TITLE
TeX Live 2023 outdated

### ISSUE THREAD

**Issue by TheLethalGoose** [qdm12/latexdevcontainer#62]
There is a problem with the devcontainer latex version.
There was, probably, a Latex update and now the command tlmgr install <package name> doesn't work anymore and throw
this error:

tlmgr: Local TeX Live (2023) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.

**Comment by qdm12** [comment]
Thanks for reporting the issue, and fixing it as well!

Fixed in #63

**Comment by TheLethalGoose** [comment]
Seems like the Build failed, maybe give it another push
