### ISSUE TITLE
Not able to use algorithm packages

### ISSUE THREAD

**Issue by shinokada** [qdm12/latexdevcontainer#7]
I installed `algorithmicx` when I built an image:

```
...
RUN tlmgr install mathexam setspace adjustbox xkeyval collectbox enumitem lastpage algorithmicx listings && \
    texhash
...
```

I used the following code:

```
\documentclass{article}

\usepackage[margin=1in]{geometry}

\usepackage{algorithm}
\usepackage{algorithmic}

\title{Algorithms}
\author{Name}
\date{}

\begin{document}
\maketitle
\section{Algorithm 1}

\begin{algorithmic}[1]
	\State first line
	\Statex continuing first line
	\State \Call{Proc}{a1, a2}
	\State \Output Hello World!
\end{algorithmic}

\end{document}
```
In the OUTPUT it returns the following error:

> ! LaTeX Error: File `algorithm.sty' not found.

![image](https://user-images.githubusercontent.com/147320/96356106-088f4000-1125-11eb-95e2-bf837227747a.png)

I also tried `algpseudocodex` as well, but it didn't work either.

When I check installed packages by `tlmgr list --only-installed`, the packages are in the list.

![image](https://user-images.githubusercontent.com/147320/96356101-ded61900-1124-11eb-9df3-900cf9e0b6a9.png)

**Comment by qdm12** [comment]
Can you please the steps again by re-pulling `:latest`? It seems #10 might solved it

**Comment by michidk** [comment]
The `algorithmicx` and ``algorithm` packages work fine for me.

**Comment by ncvescera** [comment]
@shinokada the `algorithmic` package works fine !

I tested with the latest version (a84253c) of the repo and this code:

```latex
\documentclass{article}

\usepackage[margin=1in]{geometry}

\usepackage{algorithm}
\usepackage{algorithmic}

\title{Algorithms}
\author{Name}
\date{}

\begin{document}
\maketitle
\section{Algorithm 1}

\begin{algorithmic}[1]
    \FORALL{$i$ such that $0\leq i\leq 10$}
    \STATE carry out some processing
    \ENDFOR
\end{algorithmic}

\end{document}
```
It works.

I think you have some problems with the code and the needed packages:

1. **code**:
> I used the following code:
> 
> ```
> \documentclass{article}
> 
> \usepackage[margin=1in]{geometry}
> 
> \usepackage{algorithm}
> \usepackage{algorithmic}
> 
> \title{Algorithms}
> \author{Name}
> \date{}
> 
> \begin{document}
> \maketitle
> \section{Algorithm 1}
> 
> \begin{algorithmic}[1]
> 	\State first line
> 	\Statex continuing first line
> 	\State \Call{Proc}{a1, a2}
> 	\State \Output Hello World!
> \end{algorithmic}
> 
> \end{document}
> ```
Inside the `algorithmic` block you have to use all capslock commands: `\STATE`, `\WHILE`, `\IF`, ...
For more info and the complete set of commands see [algorithmic docs](http://mirror.ox.ac.uk/sites/ctan.org/macros/latex/contrib/algorithms/algorithms.pdf)

2. **packages**:
> I installed `algorithmicx` when I built an image:
> 
> ```
> ...
> RUN tlmgr install mathexam setspace adjustbox xkeyval collectbox enumitem lastpage algorithmicx listings && \
>     texhash
> ...
> ```
You also need `algorithms` and `float`.
